name: this will trigger on push and PR

on: 
  push:
    branches:
      -main

  pull_request:
    branches:
      -main

jobs:
  echo-message:
    runs-on: ubuntu-latest
  steps:
    name: echo Slowakei
    shell: bash
    run: echo "Slowakei"
    
