name: Trigger Workflow on Environment
on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Target environment"
        required: true
        type: environment

jobs:
    print_repository:
      name: "Testing environment dispatch"
      runs-on: ubuntu-latest
      steps:
        - name: "print triggering user"
          run: echo "This is the logged-in-user ${{github.event.workflow_dispatch.user.login}}"
