name: New Conditional Jobs

on: 
    workflow_dispatch

jobs: 
    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: print haha
              run: echo "haha"
              if: github.ref == 'refs/heads/main'
            
            - name: print bbbb
              run: echo "bbbb"
              if: github.ref != 'refs/heads/main'
            
