name: Trigger on Webhook

on:
  repository_dispatch:
    types:
      - custom-webhook

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: echo Slowakei
        shell: bash
        run: echo "This is eventtype customWeb"
          