name: Example commands

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
     - name: "Group Logging"
       run: |
        echo "::group::My Group message"
        echo "Msg 1"
        echo "Msg 2"
        echo "::endgroup::"
     - name: "Step 1"
       run: echo "MY_VAL=hello" >> $GITHUB_KOKOT
     - name: "Step 2"
       run: echo "Value of my value is $MY_VAL"